package com.github.nill14.beancreator.util

import com.github.nill14.beancreator.builder.FieldDescriptor
import java.sql.Timestamp
import com.github.nill14.beancreator.builder.BeanDescriptor

object Utils {

	
	def setter(field: FieldDescriptor) = capName("set", field.name)
	
	def getter(field: FieldDescriptor) = {
		if (classOf[Boolean] == field.clazz)  
			capName("is", field.name)
		else capName("get", field.name)
	}
	
	def capName(prefix: String, name: String) = {
		val b = new StringBuilder
		b append prefix
		b append name.charAt(0).toUpper
		if (name.length > 1) b append name.substring(1)
		b.toString
	}
	
	def copyrightHeader(w: IndentWriter) {
		val now = new Timestamp(System.currentTimeMillis)
		w println "/* DO NOT MODIFY THIS FILE!"
		w println "The content is generated. Your changes may be lost."
		w println s"Generated by com.github.nill14:bean-creator ${now} */"
		w.println 
	}
	
}