/* DO NOT MODIFY THIS FILE!
The content is generated. Your changes may be lost.
Generated by com.github.nill14:bean-creator 2013-07-11 17:02:09.21 */

package com.github.nill14.test;

import java.lang.String;

/**
 * A class javadoc comment
 */
public final class MyBean {



	/**
	 * Full Name
	 */
	private final String name = "Hello";


	/**
	 * Comment
	 */
	private final int age = 35;


	/**
	 * A fuzzy value
	 */
	private final double weight = 90.0;

	public static final Builder builder() {
		return new Builder();
	}
	public static class Builder implements org.apache.commons.lang3.builder.Builder<String> {



		/**
		 * Full Name
		 */
		protected String name = "Hello";


		/**
		 * Comment
		 */
		protected int age = 35;


		/**
		 * A fuzzy value
		 */
		protected double weight = 90.0;
		@Override
		public String build() {
			// TODO Auto-generated method stub
			return null;
		}
	}

}
