/* DO NOT MODIFY THIS FILE!
The content is generated. Your changes may be lost.
Generated by com.github.nill14:bean-creator 2013-07-12 14:35:20.212 */

package com.github.nill14.test;

import java.lang.String;

/**
 * A class javadoc comment
 */
public final class MyBean {

	/**
	 * Full Name
	 */
	private final String name;

	/**
	 * Comment
	 */
	private final int age;

	/**
	 * A fuzzy value
	 */
	private final double weight;

	private MyBean(Builder builder) {
		this.name = builder.name;
		this.age = builder.age;
		this.weight = builder.weight;
	}

	/**
	 * Full Name
	 * 
	 * @return Full Name
	 */
	public String name() {
		return name;
	}

	/**
	 * Comment
	 * 
	 * @return Comment
	 */
	public int age() {
		return age;
	}

	/**
	 * A fuzzy value
	 * 
	 * @return A fuzzy value
	 */
	public double weight() {
		return weight;
	}

	public final Builder builder() {
		return new Builder(this);
	}

	public static class Builder implements org.apache.commons.lang3.builder.Builder<MyBean> {

		/**
		 * Full Name
		 */
		protected String name = "Hello";

		/**
		 * Comment
		 */
		protected int age = 35;

		/**
		 * A fuzzy value
		 */
		protected double weight = 90.0;

		public Builder() {
		}

		private Builder(MyBean myBean) {
			this.name = myBean.name;
			this.age = myBean.age;
			this.weight = myBean.weight;
		}

		/**
		 * Full Name
		 * 
		 * @param name Full Name
		 */
		public Builder name(String name) {
			this.name = name;
			return this;
		}

		/**
		 * Comment
		 * 
		 * @param age Comment
		 */
		public Builder age(int age) {
			this.age = age;
			return this;
		}

		/**
		 * A fuzzy value
		 * 
		 * @param weight A fuzzy value
		 */
		public Builder weight(double weight) {
			this.weight = weight;
			return this;
		}

		@Override
		public MyBean build() {
			return new MyBean(this);
		}
	}

}
