/* DO NOT MODIFY THIS FILE!
The content is generated. Your changes may be lost.
Generated by com.github.nill14:bean-creator 2013-07-08 22:46:28.85 */

package com.github.nill14.test;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * A class javadoc comment
 */
public class MyBean {



	/**
	 * Full Name
	 */
	public String name;


	/**
	 * Comment
	 */
	public int age;


	/**
	 * A fuzzy value
	 */
	public double weight;


	/**
	 * Full Name
	 * 
	 * @param name Full Name
	 */
	public void setName(String name) {
		this.name = name;
	}


	/**
	 * Full Name
	 * 
	 * @return Full Name
	 */
	public String getName() {
		return name;
	}


	/**
	 * Comment
	 * 
	 * @param age Comment
	 */
	public void setAge(int age) {
		this.age = age;
	}


	/**
	 * Comment
	 * 
	 * @return Comment
	 */
	public int getAge() {
		return age;
	}


	/**
	 * A fuzzy value
	 * 
	 * @param weight A fuzzy value
	 */
	public void setWeight(double weight) {
		this.weight = weight;
	}


	/**
	 * A fuzzy value
	 * 
	 * @return A fuzzy value
	 */
	public double getWeight() {
		return weight;
	}

	@Override
	public String toString() {
		ToStringBuilder b = new ToStringBuilder(this, ToStringStyle.SHORT_PREFIX_STYLE);
		return b.append(Integer.toHexString(System.identityHashCode(this)))
			.append("name", name)
			.append("age", age)
			.append("weight", weight)
			.build();
	}

}
